services:
  conduit:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-$CONDUIT_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - step-ca-network

  conduit-nginx:
    container_name: conduit-nginx
    image: nginx
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: ${WELL_KNOWN_VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${WELL_KNOWN_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${WELL_KNOWN_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${WELL_KNOWN_LETSENCRYPT_EMAIL}
    depends_on:
      - conduit
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    networks:
      - step-ca-network

configs:
  nginx-config:
    content: |
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;

      events {
        worker_connections 16384;
        multi_accept on;
        use epoll;
      }
      http {
        server {
          server_name ${WELL_KNOWN_VIRTUAL_HOST};
          listen      80 default_server;

          location ~ ^/.well-known/(.*)$ {
            proxy_pass http://conduit:${CONDUIT_PORT};
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
            proxy_set_header X-Forwarded-Host $$host;
          }

          location ~ ^/_matrix/(.*)$ {
            proxy_pass http://conduit:${CONDUIT_PORT};
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
            proxy_set_header X-Forwarded-Host $$host;
          }

          location / {
            return 404;
          }
        }
      }

networks:
  step-ca-network:
    external: true
